// SINGLE SOURCE OF TRUTH for the demo dot styling.
//
// Pulls the status-dot rules + the two @keyframes straight out of the REAL app
// stylesheet (src/App.css) and emits `_dots.generated.css`, so the demo dots
// stay pixel-identical to the shipped app even if its color tokens change. The
// probe's hand-copied dots were the thing this fixes.
//
// Two modes:
//   node extract-dot-css.mjs            # (re)generate _dots.generated.css
//   node extract-dot-css.mjs --check    # drift-guard: regenerate in memory, diff
//                                        # against the committed file, exit 1 on drift
//
// What it extracts from src/App.css (matched by selector NAME, not line number,
// so it survives edits elsewhere in App.css):
//   - .status-dot, .status-dot-running, -idle, -awaiting, -unknown  (rule blocks)
//   - @keyframes status-breathe, @keyframes status-blink
// It DELIBERATELY drops the `@media (prefers-reduced-motion: no-preference)`
// wrapper that gates the animations in the app, re-attaching the two `animation:`
// declarations unconditionally — the capture context forces no-preference anyway,
// but unwrapping makes the generated CSS self-contained + obvious.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseArgs } from "./args.mjs";

const APP_CSS = resolve(import.meta.dirname, "../../src/App.css");
const OUT = resolve(import.meta.dirname, "_dots.generated.css");

// Extract a top-level `selector { ... }` block by its exact selector text.
// Brace-balanced so nested rules (none here, but robust) don't truncate early.
function extractBlock(css, selector) {
  const start = css.indexOf(selector);
  if (start === -1)
    throw new Error(
      `extract-dot-css: selector not found in App.css: ${selector}`,
    );
  const braceOpen = css.indexOf("{", start);
  if (braceOpen === -1)
    throw new Error(`extract-dot-css: no '{' after ${selector}`);
  let depth = 0;
  for (let i = braceOpen; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}") {
      depth--;
      if (depth === 0) return css.slice(start, i + 1);
    }
  }
  throw new Error(`extract-dot-css: unbalanced braces extracting ${selector}`);
}

// Pull the single `animation: …;` declaration out of `selector`'s rule block
// within `css` (used to source the animation timing/easing from App.css's
// @media block rather than hand-copying it). Returns e.g.
// "animation: status-breathe 1.8s ease-in-out infinite;".
function pickAnimation(css, selector) {
  const block = extractBlock(css, selector + " ");
  const m = block.match(/animation:\s*[^;]+;/);
  if (!m)
    throw new Error(
      `extract-dot-css: no animation: declaration in ${selector}`,
    );
  return m[0].replace(/\s+/g, " ").trim();
}

function generate() {
  const css = readFileSync(APP_CSS, "utf8");

  // Dot rule blocks (sourced verbatim — colors/shadows/sizes come from the app).
  const rules = [
    ".status-dot ", // trailing space avoids matching .status-dot-running etc.
    ".status-dot-running ",
    ".status-dot-idle ",
    ".status-dot-awaiting ",
    ".status-dot-unknown ",
  ].map((sel) => extractBlock(css, sel).trim());

  // The two keyframes (sourced verbatim — the breathe/blink curves come from the app).
  const breathe = extractBlock(css, "@keyframes status-breathe").trim();
  const blink = extractBlock(css, "@keyframes status-blink").trim();

  // The app gates the two `animation:` declarations behind
  // @media (prefers-reduced-motion: no-preference). We SOURCE them from inside
  // that media block (not hand-copy — the timing/easing must track App.css too),
  // and re-attach them UNWRAPPED so the generated CSS animates regardless of the
  // consuming context's media state.
  const mediaBlock = extractBlock(
    css,
    "@media (prefers-reduced-motion: no-preference)",
  );
  const runningAnim = pickAnimation(mediaBlock, ".status-dot-running");
  const awaitingAnim = pickAnimation(mediaBlock, ".status-dot-awaiting");
  const animations = [
    `.status-dot-running { ${runningAnim} }`,
    `.status-dot-awaiting { ${awaitingAnim} }`,
  ].join("\n");

  return [
    "/* GENERATED by tooling/demo/extract-dot-css.mjs from src/App.css — DO NOT EDIT.",
    "   Single source of truth for the demo dot styling. Run `node extract-dot-css.mjs`",
    "   to regenerate; `--check` drift-guards it in verify-auto. */",
    "",
    ...rules,
    "",
    breathe,
    "",
    blink,
    "",
    "/* animations re-attached unconditionally (App.css gates them behind",
    "   @media prefers-reduced-motion: no-preference; capture forces no-preference). */",
    animations,
    "",
  ].join("\n");
}

const a = parseArgs();
const generated = generate();

if (a.check) {
  let committed;
  try {
    committed = readFileSync(OUT, "utf8");
  } catch {
    console.error(
      `extract-dot-css --check: ${OUT} missing — run \`node extract-dot-css.mjs\` first.`,
    );
    process.exit(1);
  }
  if (committed !== generated) {
    console.error(
      "extract-dot-css --check: DRIFT — _dots.generated.css is out of sync with src/App.css.\n" +
        "Run `node extract-dot-css.mjs` to regenerate.",
    );
    process.exit(1);
  }
  console.log("extract-dot-css --check: in sync with src/App.css ✓");
} else {
  writeFileSync(OUT, generated);
  console.log(`extract-dot-css: wrote ${OUT} (sourced from src/App.css)`);
}
