//! Claudesk time-analytics store — the write side of M9 (absorb `claude-time`).
//!
//! This is the **second, gated consumer** of the [`HookEvent`](crate::hook_socket::
//! HookEvent) stream (the first is `status_broadcaster`, which drives the live dots).
//! Where the status path maps an event to a dot state and drops the rest, this path
//! persists EVERY event as a row in a per-identity SQLite DB — but **only when the
//! tracking toggle is ON** (M9 decision 3; the toggle itself is WP5, WP2 builds the
//! gate call-site + defaults it OFF). The reclassifier (WP3) reads these rows.
//!
//! ## Why Rust owns the write (not the Perl hook)
//! `claude-time`'s hook wrote SQLite directly via a `sqlite3` subprocess. Claudesk
//! keeps the Perl hook a pure socket-forwarder (no `sqlite3` dep, no per-event
//! process spawn) and does the INSERT here — one long-lived connection, WAL, typed
//! errors. See `CLAUDE.md` + `docs/product/wp1-time-analytics-probe-outcome.md` §(d).
//!
//! ## Schema (one `events` table, WP2.5-ready)
//! `events(ts, session_id, cwd, event, tool_name, agent_type, source, meta)` —
//! `claude-time`'s shape PLUS a **`source` discriminator column** so WP2.5 can write
//! Claudesk-native-signal rows (`source = "claudesk-native"`) into the SAME table;
//! the CC-hook rows this module writes carry `source = "cc-hook"`. `meta` is a JSON
//! blob holding the event-specific extras (`prompt_length_chars` / `tool_use_id` /
//! `source` tag). Keeping one table + a `source` column (vs. a sibling table) means
//! WP3/WP4 read one stream (WBS "Native-signal schema shape" lean).
//!
//! ## Privacy invariant
//! A row NEVER stores prompt text or tool I/O — only `prompt_length_chars` (a
//! length) reaches `meta`. [`event_to_row`] reads `HookEvent::prompt_length_chars`,
//! never `HookEvent::prompt`. Pinned by [`tests::row_never_carries_prompt_text`].
//!
//! ## Layout (mirrors `config_store` / `hook_socket`)
//! - Pure functions here ([`event_to_row`], [`bootstrap`], [`insert_row`]) operate on
//!   a `rusqlite::Connection` so they unit-test against an in-memory DB with no app.
//! - The `AppHandle`-bound path resolution + the managed holder + the gated drain
//!   live in [`commands`].

pub mod commands;
// M9 WP4: the segment-model query layer — reads `events` rows for a window, runs the
// WP3 reclassifier, emits the DayPayload/WeekPayload/RangePayload segment-model DTOs.
pub mod query;

use rusqlite::Connection;
use serde_json::json;

use crate::hook_socket::HookEvent;

/// The `source` tag stamped on every row this module writes — the CC-hook event
/// stream. WP2.5 will write native-signal rows with a different tag into the same
/// table; the discriminator lets WP3/WP4 tell the two apart.
pub const SOURCE_CC_HOOK: &str = "cc-hook";

// WP2.5 native-signal STORE layer (built Phase 1) is FULLY WIRED as of Phase 4 — no
// `#[allow(dead_code)]` remains. Callers: focus handler (`record_focus_change`, Phase 2),
// `time_set_active_context` (`ActiveSurface`, Phases 2/4), `cc_input`
// (`record_keystroke_activity`, Phase 3), launch commands (`record_external_launch`,
// Phase 4). Every `NativeSignal` variant + `NativeLaunchTool` + all helpers are live.

/// The `source` tag stamped on every **Claudesk-native** signal row (M9 WP2.5): the
/// second event source, capturing what `claude-time` could only infer (window
/// focus/blur, real PTY keystroke activity, active surface, Claudesk-initiated
/// external launches). Written into the SAME `events` table as the CC-hook rows —
/// the `source` discriminator lets WP3's reclassifier read one stream and tell the
/// two sources apart. See [`NativeSignal`] for the event kinds.
pub const SOURCE_CLAUDESK_NATIVE: &str = "claudesk-native";

/// Epoch-ms "now" for **native-signal** rows. Unlike CC-hook rows (whose `ts` comes
/// from the hook-side `timestamp`), native signals are generated by Claudesk itself,
/// so they stamp their own send-time here — they NEVER hit [`event_to_row`]'s
/// epoch-0 fallback. Uses `SystemTime` (available in the app, unlike workflow
/// scripts). A pre-1970 clock (impossible in practice) clamps to 0.
pub fn now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// The Claudesk-native signal kinds WP2.5 captures. Each maps to a [`TimeRow`] via
/// [`native_row`], carrying `source = "claudesk-native"` and the signal's extras in
/// the `meta` JSON blob. **Privacy invariant (extends WP2): counts / timing /
/// attribution ONLY — never keystroke content, never a launched file path beyond the
/// attributed workspace.** The variants deliberately carry only enumerable/numeric
/// fields so there is no channel for content to leak.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NativeSignal {
    /// The Claudesk main window gained focus. Attributed to the currently-active
    /// workspace/surface (from the frontend's `time_set_active_context`), if any.
    WindowFocus,
    /// The Claudesk main window lost focus. Paired with a later [`WindowFocus`] so
    /// WP3 can derive blur *duration*; `preceded_by_launch` lets WP3 resolve the
    /// "blur-but-working" case (operator popped an external tool then looked at it).
    WindowBlur { preceded_by_launch: bool },
    /// Real bytes flowed into a workspace's CC/terminal PTY (via `cc_input`). Carries
    /// the BYTE COUNT only — never the bytes. Attributed to the active workspace.
    KeystrokeActivity { byte_count: usize },
    /// The active right-panel surface changed (editor / diff / terminal). Lets WP3
    /// measure "editor-active + no keystrokes ⇒ reading code" vs terminal-following.
    ActiveSurface,
    /// Claudesk launched an external tool for a workspace (Sublime Text / Merge /
    /// Finder). The tool IDENTITY only — never the launched path. The signal a
    /// subsequent blur can be correlated against.
    ExternalLaunch { tool: NativeLaunchTool },
    /// A workspace's CC session was torn down by Claudesk — an explicit **session-end
    /// marker** (M9 WP6.5 signal 1). Written when Claudesk kills a PTY on workspace-close
    /// (`cc_kill`) or app-quit (`kill_all` on `CloseRequested`). This is the authoritative,
    /// synchronously-recorded end the reclassifier's [`crate::reclassify::authoritative_end`]
    /// reads at top precedence — the backstop for the hard-kill/crash case where CC cannot
    /// emit a `SessionEnd` (live-confirmed 2026-07-08). The row carries only the session
    /// handle + `now_ms()` (privacy: no content).
    WorkspaceClose,
}

/// Which Claudesk-initiated external tool a [`NativeSignal::ExternalLaunch`] marks.
/// A closed enum (not a free string) so the launch signal cannot carry a path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativeLaunchTool {
    SublimeText,
    SublimeMerge,
    Finder,
}

impl NativeLaunchTool {
    /// The stable `tool` string persisted in `meta` (matches WP3's expected vocab).
    pub fn as_str(self) -> &'static str {
        match self {
            NativeLaunchTool::SublimeText => "sublime",
            NativeLaunchTool::SublimeMerge => "smerge",
            NativeLaunchTool::Finder => "finder",
        }
    }
}

/// The attribution context a native signal is stamped with — the active workspace
/// (from the frontend's `time_set_active_context`) plus, for keystroke rows, the
/// originating PTY `session_id`. All fields optional: a focus event may fire before
/// any workspace is active; a launch may target a workspace with no live session.
///
/// **Privacy:** `workspace_id` and `session_id` are opaque handles (`ws-…` / `cc-…`),
/// `cwd` is the project dir already stored on CC-hook rows — nothing content-bearing.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct NativeContext {
    pub workspace_id: Option<String>,
    pub surface: Option<String>,
    pub cwd: Option<String>,
    pub session_id: Option<String>,
}

/// Map a [`NativeSignal`] + its attribution [`NativeContext`] to the [`TimeRow`] to
/// persist. Stamps `source = "claudesk-native"` and `ts = now_ms()` (native signals
/// carry their own send-time — see [`now_ms`]). The `event` column is the signal
/// kind; signal-specific extras + attribution go into `meta`.
///
/// **Privacy:** every value written to `meta` here is a count, an enum tag, a bool,
/// or an opaque handle — never keystroke content, never a file path beyond `cwd`.
/// Pinned by [`tests::native_row_never_carries_content`].
pub fn native_row(signal: &NativeSignal, ctx: &NativeContext) -> TimeRow {
    let mut meta = serde_json::Map::new();
    if let Some(ws) = &ctx.workspace_id {
        meta.insert("workspace_id".into(), json!(ws));
    }
    if let Some(surface) = &ctx.surface {
        meta.insert("surface".into(), json!(surface));
    }

    let event = match signal {
        NativeSignal::WindowFocus => "WindowFocus",
        NativeSignal::WindowBlur { preceded_by_launch } => {
            meta.insert("preceded_by_launch".into(), json!(preceded_by_launch));
            "WindowBlur"
        }
        NativeSignal::KeystrokeActivity { byte_count } => {
            // COUNT only — never the bytes (the privacy invariant).
            meta.insert("byte_count".into(), json!(byte_count));
            "KeystrokeActivity"
        }
        NativeSignal::ActiveSurface => "ActiveSurface",
        NativeSignal::ExternalLaunch { tool } => {
            meta.insert("tool".into(), json!(tool.as_str()));
            "ExternalLaunch"
        }
        // M9 WP6.5 signal 1 — must match `reclassify::EVENT_WORKSPACE_CLOSE`. No extra meta
        // beyond the attribution already inserted above; the session handle (in
        // `session_id`) + `ts` ARE the marker.
        NativeSignal::WorkspaceClose => "WorkspaceClose",
    };

    let meta = if meta.is_empty() {
        None
    } else {
        Some(serde_json::Value::Object(meta).to_string())
    };

    TimeRow {
        ts: now_ms(),
        // Keystroke rows carry the originating PTY session; other native signals are
        // window/workspace-level (empty session_id). The column is NOT NULL, so an
        // absent session is the empty string (matches the CC-hook rows' non-null cwd).
        session_id: ctx.session_id.clone().unwrap_or_default(),
        cwd: ctx.cwd.clone().unwrap_or_default(),
        event: event.to_string(),
        tool_name: None,
        agent_type: None,
        source: SOURCE_CLAUDESK_NATIVE.to_string(),
        meta,
    }
}

/// Schema DDL — idempotent (`IF NOT EXISTS`). Mirrors `claude-time`'s `events` table
/// plus the `source` discriminator column (M9 WP2.5-ready). Run by [`bootstrap`].
///
/// `WAL` + a busy-timeout are set on the *connection* in [`commands`], not here (they
/// are connection pragmas, not schema). The two indexes mirror `claude-time`'s
/// (session+ts for per-session scans, ts for day/range scans).
const SCHEMA_SQL: &str = "\
CREATE TABLE IF NOT EXISTS events (
  ts          INTEGER NOT NULL,
  session_id  TEXT NOT NULL,
  cwd         TEXT NOT NULL,
  event       TEXT NOT NULL,
  tool_name   TEXT,
  agent_type  TEXT,
  source      TEXT NOT NULL,
  meta        TEXT
);
CREATE INDEX IF NOT EXISTS idx_session_ts ON events(session_id, ts);
CREATE INDEX IF NOT EXISTS idx_ts ON events(ts);
";

/// One persisted time-analytics row, mapped from a [`HookEvent`]. Column-parallel to
/// the `events` table. `meta` is the serialized JSON blob (or `None` when the event
/// has no extras). Built by [`event_to_row`]; written by [`insert_row`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TimeRow {
    pub ts: i64,
    pub session_id: String,
    pub cwd: String,
    pub event: String,
    pub tool_name: Option<String>,
    pub agent_type: Option<String>,
    /// Row source discriminator — [`SOURCE_CC_HOOK`] for every row this module writes.
    pub source: String,
    /// JSON blob of event-specific extras, or `None`. Never contains prompt text.
    pub meta: Option<String>,
}

/// Map a [`HookEvent`] to the [`TimeRow`] to persist, or `None` if the event carries
/// no `hook_event_name` (a malformed/empty event we never store).
///
/// The `meta` blob is assembled from the event's time-analytics fields — the SAME
/// keys `claude-time`'s hook emitted (`prompt_length_chars` / `tool_use_id` /
/// `source`) PLUS `notification_type` (the `Notification` type tag, WP3 needs it to
/// derive CC's AwaitingInput state) PLUS `reason` (the `SessionEnd` tag, M9 WP6.5) —
/// so the reclassifier reads the identical shape.
/// **Privacy: only `prompt_length_chars` (the LENGTH) is read; `HookEvent::prompt`
/// (the text) is never touched here.** `source = "cc-hook"` is stamped unconditionally.
///
/// `ts` uses the hook-side `timestamp` (epoch ms) when present, else 0 — the caller
/// (the drain thread) does not re-stamp; the hook's send-time is the event time.
pub fn event_to_row(event: &HookEvent) -> Option<TimeRow> {
    if event.hook_event_name.is_empty() {
        return None;
    }

    // Assemble meta from whichever extras this event carries. Mirrors claude-time's
    // per-event meta: UserPromptSubmit → {prompt_length_chars}; Pre/Post tool events →
    // {tool_use_id}; SessionStart → {source}; Notification → {notification_type}.
    // Multiple keys can co-exist harmlessly.
    let mut meta = serde_json::Map::new();
    if let Some(len) = event.prompt_length_chars {
        // LENGTH only — never the prompt text (the privacy invariant).
        meta.insert("prompt_length_chars".into(), json!(len));
    }
    if let Some(tuid) = &event.tool_use_id {
        meta.insert("tool_use_id".into(), json!(tuid));
    }
    if let Some(src) = &event.source {
        meta.insert("source".into(), json!(src));
    }
    if let Some(ntype) = &event.notification_type {
        // The Notification's type tag (`permission_prompt` / `elicitation_dialog` /
        // `idle_prompt` / …). The WRITER is meaning-agnostic — it just persists the tag;
        // the WP3 reclassifier decides which types mean "CC AwaitingInput" (reusing
        // `status_broadcaster`'s classifier). An enum tag, never content — same privacy
        // class as the keys above. Needed by WP3's B2/B4 human-state rule.
        meta.insert("notification_type".into(), json!(ntype));
    }
    if let Some(reason) = &event.reason {
        // The SessionEnd `reason` tag (`prompt_input_exit` / `other` / …). M9 WP6.5: the
        // session-end model honors SessionEnd as an authoritative end; the reason is
        // persisted for debugging (the derivation does not branch on it in v1). An enum-ish
        // tag, never content — same privacy class as `source`/`notification_type`.
        meta.insert("reason".into(), json!(reason));
    }
    let meta = if meta.is_empty() {
        None
    } else {
        Some(serde_json::Value::Object(meta).to_string())
    };

    Some(TimeRow {
        ts: event.timestamp.map(|t| t as i64).unwrap_or(0),
        session_id: event.session_id.clone(),
        cwd: event.cwd.clone(),
        event: event.hook_event_name.clone(),
        tool_name: event.tool_name.clone(),
        agent_type: event.agent_type.clone(),
        source: SOURCE_CC_HOOK.to_string(),
        meta,
    })
}

/// Create the `events` table + indexes if absent (idempotent). Called once when the
/// connection opens (in [`commands::TimeStore`]). `execute_batch` runs the multi-
/// statement DDL in one call.
pub fn bootstrap(conn: &Connection) -> rusqlite::Result<()> {
    conn.execute_batch(SCHEMA_SQL)
}

/// INSERT one [`TimeRow`]. Parameterized (no string interpolation — SQL-injection-
/// safe by construction, unlike claude-time's hand-quoted `sql_q`). The caller gates
/// on the tracking toggle BEFORE calling this ([`commands::write_gated`]).
pub fn insert_row(conn: &Connection, row: &TimeRow) -> rusqlite::Result<()> {
    conn.execute(
        "INSERT INTO events (ts, session_id, cwd, event, tool_name, agent_type, source, meta)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
        rusqlite::params![
            row.ts,
            row.session_id,
            row.cwd,
            row.event,
            row.tool_name,
            row.agent_type,
            row.source,
            row.meta,
        ],
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A `HookEvent` builder for the tests (the struct has no `Default`). Only the
    /// fields a given test cares about are overridden after construction.
    fn base_event(name: &str) -> HookEvent {
        HookEvent {
            hook_event_name: name.to_string(),
            session_id: "sess-1".to_string(),
            cwd: "/repo/proj-a".to_string(),
            timestamp: Some(1_718_000_000_000),
            prompt: None,
            message: None,
            notification_type: None,
            prompt_length_chars: None,
            tool_use_id: None,
            tool_name: None,
            agent_type: None,
            source: None,
            reason: None,
        }
    }

    /// Open an in-memory DB with the schema bootstrapped — the pure-core test rig.
    fn mem_db() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        bootstrap(&conn).unwrap();
        conn
    }

    fn row_count(conn: &Connection) -> i64 {
        conn.query_row("SELECT COUNT(*) FROM events", [], |r| r.get(0))
            .unwrap()
    }

    #[test]
    fn bootstrap_is_idempotent() {
        let conn = Connection::open_in_memory().unwrap();
        bootstrap(&conn).unwrap();
        // Second bootstrap over the same connection is a no-op (IF NOT EXISTS).
        bootstrap(&conn).unwrap();
        // The table exists and is queryable.
        assert_eq!(row_count(&conn), 0);
    }

    #[test]
    fn user_prompt_submit_row_carries_length_in_meta_not_text() {
        let mut ev = base_event("UserPromptSubmit");
        ev.prompt = Some("this is the secret prompt text".to_string());
        ev.prompt_length_chars = Some(30);
        let row = event_to_row(&ev).unwrap();

        assert_eq!(row.event, "UserPromptSubmit");
        assert_eq!(row.source, SOURCE_CC_HOOK);
        assert_eq!(row.ts, 1_718_000_000_000);
        let meta = row.meta.expect("UserPromptSubmit has meta");
        let parsed: serde_json::Value = serde_json::from_str(&meta).unwrap();
        assert_eq!(parsed["prompt_length_chars"], json!(30));
        // The prompt TEXT must appear NOWHERE in the row.
        assert!(!meta.contains("secret"), "meta must not carry prompt text");
    }

    #[test]
    fn row_never_carries_prompt_text() {
        // The privacy invariant, stated as a test: whatever the prompt is, no field
        // of the mapped row contains it. Only the length reaches meta.
        let mut ev = base_event("UserPromptSubmit");
        ev.prompt = Some("PROMPTBODY-DO-NOT-PERSIST".to_string());
        ev.prompt_length_chars = Some(25);
        let row = event_to_row(&ev).unwrap();
        let all_text = format!(
            "{}|{}|{}|{}|{}|{}",
            row.session_id,
            row.cwd,
            row.event,
            row.tool_name.unwrap_or_default(),
            row.agent_type.unwrap_or_default(),
            row.meta.unwrap_or_default(),
        );
        assert!(
            !all_text.contains("PROMPTBODY"),
            "no row field may contain the prompt text"
        );
    }

    #[test]
    fn pre_tool_use_row_carries_tool_fields() {
        let mut ev = base_event("PreToolUse");
        ev.tool_name = Some("Edit".to_string());
        ev.tool_use_id = Some("tu_1".to_string());
        let row = event_to_row(&ev).unwrap();
        assert_eq!(row.tool_name.as_deref(), Some("Edit"));
        let meta: serde_json::Value = serde_json::from_str(&row.meta.unwrap()).unwrap();
        assert_eq!(meta["tool_use_id"], json!("tu_1"));
    }

    #[test]
    fn subagent_row_carries_agent_type_no_meta() {
        let mut ev = base_event("SubagentStart");
        ev.agent_type = Some("Explore".to_string());
        let row = event_to_row(&ev).unwrap();
        assert_eq!(row.agent_type.as_deref(), Some("Explore"));
        // No prompt_length/tool_use_id/source → no meta blob.
        assert_eq!(row.meta, None);
    }

    #[test]
    fn session_start_row_carries_source_in_meta() {
        let mut ev = base_event("SessionStart");
        ev.source = Some("startup".to_string());
        let row = event_to_row(&ev).unwrap();
        let meta: serde_json::Value = serde_json::from_str(&row.meta.unwrap()).unwrap();
        assert_eq!(meta["source"], json!("startup"));
    }

    #[test]
    fn notification_row_carries_notification_type_in_meta() {
        // WP3 (M9): the reclassifier derives CC's AwaitingInput state from a
        // Notification's type tag, so the writer must persist it. The writer is
        // MEANING-AGNOSTIC — BOTH an input-needed type and an informational type
        // round-trip identically; the reclassifier (not this writer) decides which
        // types mean "awaiting input".
        for ntype in ["permission_prompt", "idle_prompt"] {
            let mut ev = base_event("Notification");
            ev.notification_type = Some(ntype.to_string());
            ev.message = Some("NOTIFMSG-DO-NOT-PERSIST".to_string());
            let row = event_to_row(&ev).unwrap();
            assert_eq!(row.event, "Notification");
            let meta = row.meta.expect("Notification with a type has meta");
            let parsed: serde_json::Value = serde_json::from_str(&meta).unwrap();
            assert_eq!(parsed["notification_type"], json!(ntype));
            // Privacy: the Notification's human-readable MESSAGE body is never persisted
            // (only the type TAG is). Pins that adding notification_type didn't open a
            // content channel via `message` (row_never_carries_prompt_text guards `prompt`,
            // not `message` — this closes that Notification-specific gap).
            assert!(
                !meta.contains("NOTIFMSG"),
                "Notification message body must not appear in the row meta"
            );
        }
    }

    #[test]
    fn session_end_row_carries_reason_in_meta_not_message() {
        // M9 WP6.5: a SessionEnd row persists its `reason` tag (prompt_input_exit / other)
        // into meta so the session-end model + debugging can read it. The event's message
        // body (if any) is NOT persisted — same privacy class as notification_type.
        for reason in ["prompt_input_exit", "other"] {
            let mut ev = base_event("SessionEnd");
            ev.reason = Some(reason.to_string());
            ev.message = Some("ENDMSG-DO-NOT-PERSIST".to_string());
            let row = event_to_row(&ev).unwrap();
            assert_eq!(row.event, "SessionEnd");
            assert_eq!(row.source, SOURCE_CC_HOOK);
            let meta = row.meta.expect("SessionEnd with a reason has meta");
            let parsed: serde_json::Value = serde_json::from_str(&meta).unwrap();
            assert_eq!(parsed["reason"], json!(reason));
            assert!(
                !meta.contains("ENDMSG"),
                "SessionEnd message body must not appear in the row meta"
            );
        }
    }

    #[test]
    fn session_end_row_without_reason_has_no_reason_key() {
        // A SessionEnd with no reason tag → no reason in meta (and no meta blob at all).
        let ev = base_event("SessionEnd");
        let row = event_to_row(&ev).unwrap();
        assert_eq!(row.meta, None);
    }

    #[test]
    fn notification_row_without_type_has_no_notification_type_key() {
        // A Notification with no type tag (absent field) → no notification_type in meta
        // (and, with no other extras, no meta blob at all). Guards the optional-key
        // pattern: we never write a null/empty tag.
        let ev = base_event("Notification");
        let row = event_to_row(&ev).unwrap();
        assert_eq!(row.meta, None);
    }

    #[test]
    fn empty_event_name_maps_to_none() {
        let ev = base_event("");
        assert_eq!(event_to_row(&ev), None);
    }

    #[test]
    fn stop_row_has_no_meta_and_cc_hook_source() {
        // A plain Stop → a row with the core fields, source=cc-hook, no meta.
        let ev = base_event("Stop");
        let row = event_to_row(&ev).unwrap();
        assert_eq!(row.event, "Stop");
        assert_eq!(row.source, SOURCE_CC_HOOK);
        assert_eq!(row.meta, None);
        assert_eq!(row.tool_name, None);
        assert_eq!(row.agent_type, None);
    }

    #[test]
    fn insert_row_writes_exactly_one_row_with_expected_columns() {
        let conn = mem_db();
        let mut ev = base_event("UserPromptSubmit");
        ev.prompt_length_chars = Some(11);
        let row = event_to_row(&ev).unwrap();
        insert_row(&conn, &row).unwrap();

        assert_eq!(row_count(&conn), 1);
        let (event, source, cwd, meta): (String, String, String, Option<String>) = conn
            .query_row(
                "SELECT event, source, cwd, meta FROM events LIMIT 1",
                [],
                |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?)),
            )
            .unwrap();
        assert_eq!(event, "UserPromptSubmit");
        assert_eq!(source, SOURCE_CC_HOOK);
        assert_eq!(cwd, "/repo/proj-a");
        assert!(meta.unwrap().contains("prompt_length_chars"));
    }

    #[test]
    fn multiple_inserts_accumulate() {
        let conn = mem_db();
        for name in ["UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop"] {
            let row = event_to_row(&base_event(name)).unwrap();
            insert_row(&conn, &row).unwrap();
        }
        assert_eq!(row_count(&conn), 4);
        // Every row is source=cc-hook (the WP2.5 discriminator, populated).
        let distinct_sources: i64 = conn
            .query_row("SELECT COUNT(DISTINCT source) FROM events", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(distinct_sources, 1);
    }

    // ---- M9 WP2.5: native-signal rows ----------------------------------------

    fn ctx() -> NativeContext {
        NativeContext {
            workspace_id: Some("ws-1".into()),
            surface: Some("editor".into()),
            cwd: Some("/repo/proj-a".into()),
            session_id: None,
        }
    }

    #[test]
    fn now_ms_is_a_plausible_recent_epoch_ms() {
        // A real epoch-ms, not the 0 fallback: must be after 2020-01-01 (1_577_836_800_000).
        // This is what keeps native rows off event_to_row's epoch-0 path (WP2 MINOR #2).
        assert!(
            now_ms() > 1_577_836_800_000,
            "now_ms must be a real recent epoch-ms"
        );
    }

    #[test]
    fn native_row_round_trips_into_the_same_events_table_with_native_source() {
        let conn = mem_db();
        let row = native_row(&NativeSignal::WindowFocus, &ctx());
        assert_eq!(row.source, SOURCE_CLAUDESK_NATIVE);
        assert_eq!(row.event, "WindowFocus");
        assert!(row.ts > 1_577_836_800_000, "native row carries a real ts");
        insert_row(&conn, &row).unwrap();

        // Same table as the cc-hook rows — a mixed query sees both sources.
        insert_row(&conn, &event_to_row(&base_event("Stop")).unwrap()).unwrap();
        assert_eq!(row_count(&conn), 2);
        let distinct_sources: i64 = conn
            .query_row("SELECT COUNT(DISTINCT source) FROM events", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(
            distinct_sources, 2,
            "cc-hook and claudesk-native coexist in one table"
        );
    }

    #[test]
    fn native_focus_row_carries_workspace_and_surface_attribution() {
        let row = native_row(&NativeSignal::WindowFocus, &ctx());
        let meta: serde_json::Value = serde_json::from_str(&row.meta.unwrap()).unwrap();
        assert_eq!(meta["workspace_id"], json!("ws-1"));
        assert_eq!(meta["surface"], json!("editor"));
    }

    #[test]
    fn native_blur_row_carries_preceded_by_launch_flag() {
        let row = native_row(
            &NativeSignal::WindowBlur {
                preceded_by_launch: true,
            },
            &ctx(),
        );
        assert_eq!(row.event, "WindowBlur");
        let meta: serde_json::Value = serde_json::from_str(&row.meta.unwrap()).unwrap();
        assert_eq!(meta["preceded_by_launch"], json!(true));
    }

    #[test]
    fn native_keystroke_row_carries_byte_count_and_session_not_content() {
        let mut c = ctx();
        c.session_id = Some("cc-3".into());
        let row = native_row(&NativeSignal::KeystrokeActivity { byte_count: 42 }, &c);
        assert_eq!(row.event, "KeystrokeActivity");
        assert_eq!(
            row.session_id, "cc-3",
            "keystroke row attributed to its PTY session"
        );
        let meta: serde_json::Value = serde_json::from_str(&row.meta.unwrap()).unwrap();
        assert_eq!(meta["byte_count"], json!(42));
    }

    #[test]
    fn native_launch_row_carries_tool_identity() {
        for (tool, expected) in [
            (NativeLaunchTool::SublimeText, "sublime"),
            (NativeLaunchTool::SublimeMerge, "smerge"),
            (NativeLaunchTool::Finder, "finder"),
        ] {
            let row = native_row(&NativeSignal::ExternalLaunch { tool }, &ctx());
            assert_eq!(row.event, "ExternalLaunch");
            let meta: serde_json::Value = serde_json::from_str(&row.meta.unwrap()).unwrap();
            assert_eq!(meta["tool"], json!(expected));
        }
    }

    #[test]
    fn native_workspace_close_row_is_the_session_end_marker() {
        // M9 WP6.5 signal 1: WorkspaceClose maps to event "WorkspaceClose" on a
        // claudesk-native row, matching reclassify::EVENT_WORKSPACE_CLOSE (the reclassifier
        // reads it at top precedence). The session handle + ts ARE the marker — no
        // content. Attributed to the session it closes.
        let mut c = ctx();
        c.session_id = Some("cc-7".into());
        let row = native_row(&NativeSignal::WorkspaceClose, &c);
        assert_eq!(row.event, "WorkspaceClose");
        assert_eq!(row.event, crate::reclassify::EVENT_WORKSPACE_CLOSE);
        assert_eq!(row.source, SOURCE_CLAUDESK_NATIVE);
        assert_eq!(row.session_id, "cc-7", "marker attributed to the closed session");
        assert!(row.ts > 1_577_836_800_000, "carries a real ts");
        assert_eq!(row.tool_name, None);
        assert_eq!(row.agent_type, None);
    }

    #[test]
    fn native_row_never_carries_content() {
        // The privacy invariant, stated as a test on STRUCTURED fields (not a bare
        // !contains substring check — that was WP2 MINOR #1's weakness). The
        // NativeSignal enum only carries counts/enums/bools, so there is no field
        // that COULD hold content; this test pins that no builder ever widens that.
        // We feed a keystroke of a "secret" LENGTH and assert only the count survives,
        // and that every meta VALUE is a number, bool, or a known-safe enum/handle —
        // never a free-form content string.
        let mut c = ctx();
        c.session_id = Some("cc-1".into());
        // The "content" would be 11 bytes of "SECRETKEYS!" — only the length 11 lands.
        let row = native_row(&NativeSignal::KeystrokeActivity { byte_count: 11 }, &c);
        let meta: serde_json::Value = serde_json::from_str(row.meta.as_ref().unwrap()).unwrap();

        // byte_count is present and numeric.
        assert_eq!(meta["byte_count"], json!(11));
        // Every meta value is a safe type: number, bool, or one of the known
        // attribution strings (workspace_id / surface). No unexpected content string.
        let allowed_string_keys = ["workspace_id", "surface"];
        for (k, v) in meta.as_object().unwrap() {
            match v {
                serde_json::Value::Number(_) | serde_json::Value::Bool(_) => {}
                serde_json::Value::String(_) => assert!(
                    allowed_string_keys.contains(&k.as_str()),
                    "meta key {k} is a string but not a known-safe attribution field"
                ),
                other => panic!("unexpected meta value type for {k}: {other:?}"),
            }
        }
        // And the row's own text columns never carry content: tool_name/agent_type
        // are None for a keystroke row; session_id/cwd are opaque handles/paths.
        assert_eq!(row.tool_name, None);
        assert_eq!(row.agent_type, None);
    }

    #[test]
    fn native_row_with_empty_context_has_no_null_columns() {
        // A focus event before any workspace is active: empty attribution. The NOT NULL
        // session_id/cwd columns must be the empty string, not a NULL that would fail
        // the insert. Prove it inserts.
        let conn = mem_db();
        let row = native_row(&NativeSignal::ActiveSurface, &NativeContext::default());
        assert_eq!(row.session_id, "");
        assert_eq!(row.cwd, "");
        insert_row(&conn, &row).unwrap();
        assert_eq!(row_count(&conn), 1);
    }
}
